spring:
  datasource:
    url: Server=tcp:nagarro-chandan.database.windows.net,1433;Initial Catalog=exitTest;Persist Security Info=False;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
    username: chandan
    password: sahil@11
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect
server:
  port: 9000